[versions]
assertj_joda_time = "2.2.0"

[libraries]
assertj-core = { module = "org.assertj:assertj-core", version = "3.10.0" }
assertj-joda-time = { module = "org.assertj:assertj-joda-time", version.ref = "assertj_joda_time" }
